Support transferring multiple store paths in one operation

diff --git a/scripts/disnix-copy-closure.in b/scripts/disnix-copy-closure.in
--- a/scripts/disnix-copy-closure.in
+++ b/scripts/disnix-copy-closure.in
@@ -24,8 +24,8 @@ set -o pipefail
 showUsage()
 {
     cat <<EOF
-Usage: $0 [OPTION] --to --target TARGET path
-  or: $0 [OPTION] --from --target TARGET path
+Usage: $0 [OPTION] --to --target TARGET paths
+  or: $0 [OPTION] --from --target TARGET paths
 
 The command \`disnix-copy-closure' copies a Nix store component and all its
 intra-dependencies to or from a given target machine through a Disnix
@@ -105,16 +105,13 @@ do
     shift
 done
 
-# Get component name
+# Shift to get all non-option parameters reflecting Nix store paths
 shift
-component=$1
 
 # Autoconf settings
-
 export prefix=@prefix@
 
 # Import checks
-
 source @datadir@/@PACKAGE@/checks
 
 # Validate the given options
@@ -128,9 +125,9 @@ fi
 checkTarget
 checkClientInterface
 
-if [ "$component" = "" ]
+if [ "$@" = "" ]
 then
-    echo "ERROR: A Nix component must be specified!" >&2
+    echo "ERROR: At least one Nix store path must be specified!" >&2
     exit 1
 fi
 
@@ -141,7 +138,7 @@ checkTmpDir
 if [ "$to" = "1" ]
 then
     # Resolve the store path of the given file
-    storePath=`nix-store --query --resolve $component`
+    storePath=`nix-store --query --resolve $@`
 
     # Query the requisites of the given component
     requisites=`nix-store --query --requisites $storePath`
@@ -165,7 +162,7 @@ then
     fi
 else
     # Query the requisites of the given component
-    requisites=`$interface --target $target --query-requisites $component`
+    requisites=`$interface --target $target --query-requisites $@`
     
     # Query all the invalid paths on this machine
     invalidPaths=`nix-store --check-validity --print-invalid $requisites`
